name: Validate Lesson

on:
  push:
    branches:
      - staging

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout student code
        uses: actions/checkout@v3

      - name: Get test binary
        run: |
          curl -o test_binary.tar.gz https://test-binary.codeling.dev/main.tar.gz
          tar xzf test_binary.tar.gz
          chmod +x main

      - name: Setup test binary
        run: ./main -command setup

      - name: Setup Python
        if: ${{ env.SETUP_ACTION == '/actions/setup-python' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: verify python
        run: python --version
