name: Validate Lesson

on:
  push:
    branches:
      - staging

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout student code
        uses: actions/checkout@v3

      - name: Get test binary
        run: |
          curl -o test_binary.tar.gz https://test-binary.codeling.dev/main.tar.gz
          tar xzf test_binary.tar.gz
          chmod +x test_binary

      - name: Setup test binary
        run: ./test_binary -command setup

      - name: echo SETUP_ACTION
        run: echo $SETUP_ACTION
